linters:
  enable:
    - revive
    - gofmt
    - govet
    - errcheck
    - staticcheck

run:
  deadline: 5m
  skip-dirs-use-default: true
  skip-dirs:
    - "go/pkg/mod"

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false

issues:
  exclude-files:
    - ".*\\.gen\\.go$"
    - ".*\\.pb\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - golint
